export const BALANCE = {
  // 본체
  PLAYER_SPEED: 72, // 120에서 -40% (플레이테스트 후 템포 조정)
  PLAYER_HP_MAX: 100,
  PLAYER_INVULN_DURATION: 1.0,
  PLAYER_RADIUS: 8,
  PLAYER_SIZE: 12,

  // 포탑
  TURRET_ROTATE_SPEED: 63, // 90에서 -30%
  TURRET_FIRE_INTERVAL: 0.6,
  BULLET_SPEED: 320,
  BULLET_DAMAGE: 10,
  BULLET_LIFETIME: 1.5,
  BULLET_RADIUS: 3,

  // 방향 선택
  DIRECTION_CANDIDATES: 12,
  ENEMY_AVOID_RADIUS: 200,
  ENEMY_AVOID_WEIGHT: 800,
  EXCLUDE_CURRENT_DIR_TOLERANCE: 15,

  // 적
  ENEMY_SPEED: 60,
  // POC: 총알 데미지보다 1 큼. "탄환 화력" 업그레이드 1회로 1타 처치 성립
  ENEMY_HP: 11,
  ENEMY_DAMAGE: 10,
  ENEMY_RADIUS: 7,
  ENEMY_SPAWN_INTERVAL: 5.0,
  ENEMY_SPAWN_INTERVAL_MIN: 1.5,
  ENEMY_SPAWN_INTERVAL_DECAY: 60.0, // 매 60초마다 인터벌이 1초씩 줄어든다 (clamp = MIN)
  ENEMY_SPAWN_COUNT_INITIAL: 5,
  ENEMY_SPAWN_COUNT_GROWTH: 1,
  ENEMY_SPAWN_DISTANCE: 400,

  // 경험치
  XP_ORB_PICKUP_RADIUS: 80,
  XP_ORB_SPEED: 240,
  XP_ORB_RADIUS: 4,
  XP_PER_KILL: 5,
  XP_LEVELUP_BASE: 20,
  XP_LEVELUP_GROWTH: 1.4,

  // 카메라
  CAMERA_LERP: 0.1,

  // 색상
  COLOR_BG: '#0a0a12',
  COLOR_PLAYER: '#5fc',
  COLOR_TURRET: '#fff',
  COLOR_ENEMY: '#f33',
  COLOR_ENEMY_TARGETED: '#fb3',
  COLOR_TARGET_RING: '#fff',
  COLOR_BULLET_PLAYER: '#fe4',
  COLOR_BULLET_ENEMY: '#f3f',
  COLOR_XP_ORB: '#3ff',
  COLOR_AIM_LINE: 'rgba(255,255,255,0.15)',

  // 포탑 시각
  TURRET_LENGTH: 14,
  TURRET_WIDTH: 3,
  TARGET_RING_WIDTH: 1,
  AIM_LINE_LENGTH: 600,
} as const;
